/**
//══════════════════════════════════════════════════════════════════════════════════════════════════════//
//                                                                                                      //
//                                ＷＨＡＴＳＡＰＰ ＢＯＴ－ＭＤ ＢＥＴＡ                                      //
//                                                                                                      // 
//                                         Ｖ：0. 0. 3                                                   //
//                                                                                                      // 
//                                                                                                      //
//                     ███████╗███████╗ █████╗ ██╗         ███╗   ███╗██████╗                           //
//                     ╚════██║██╔════╝██╔══██╗██║         ████╗ ████║██╔══██╗                          //
//                     ███████║███████╗███████║██║         ██╔████╔██║██║  ██║                          //
//                     ██═════╗██╔════╝██╔══██║██║         ██║╚██╔╝██║██║  ██║                          //
//                     ███████║███████║██║  ██║███████╗    ██║ ╚═╝ ██║██████╔╝                          //
//                     ╚══════╝╚══════╝╚═╝  ╚═╝╚══════╝    ╚═╝     ╚═╝╚═════╝                           //
//                                                                                                      //
//                                                                                                      //
//                                                                                                      //
//══════════════════════════════════════════════════════════════════════════════════════════════════════//


CURRENTLY RUNNING ON BETA VERSION!!
*
   * @project_name : Zeal_Md
   * @author : Zeal 
   * @description : Zeal_Md ,A Multi-functional whatsapp user bot.
   * @version 0.0.3
*
   * Licensed under the  GPL-3.0 License;
* 
   * Created By Zeal.
   * © 2024 Zeal_Md.
* 
FROM quay.io/sampandey001/secktor
RUN git clone https://github.com/zeal-md/ZEAL-MD /root/zeal-md
WORKDIR /root/zeal-md/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
